CREATE DATABASE IF NOT EXISTS project1_db;
USE project1_db;

CREATE TABLE IF NOT EXISTS Contact (
    ContactID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL,
    Roll VARCHAR(50) NOT NULL,
    Department VARCHAR(100),
    Message TEXT NOT NULL,
    DateSubmitted DATETIME DEFAULT CURRENT_TIMESTAMP,
    IsRead TINYINT DEFAULT 0,
    Status VARCHAR(50) DEFAULT 'New'
);

CREATE TABLE IF NOT EXISTS Users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Name VARCHAR(255) NOT NULL,
    Username VARCHAR(100) NOT NULL UNIQUE,
    Password VARCHAR(255) NOT NULL,
    Email VARCHAR(255) NOT NULL UNIQUE,
    Roll VARCHAR(50) NOT NULL UNIQUE,
    Batch VARCHAR(50) NOT NULL,
    Department VARCHAR(100) NOT NULL,
    University VARCHAR(255) NOT NULL,
    Phone VARCHAR(20),
    UserType VARCHAR(50) NOT NULL DEFAULT 'User',
    Reason TEXT NOT NULL,
    DateRegistered DATETIME DEFAULT CURRENT_TIMESTAMP,
    IsActive TINYINT DEFAULT 1,
    IsVerified TINYINT DEFAULT 0,
    LastLogin DATETIME
);
